/** Server-side public StaffDeck protocol types; credentials remain in the host transport. */
export type PublicOperationInput = {
  list_tools: {};
  list_general_skills: {};
  list_knowledge_bases: {};
  create_knowledge_base: { body: { name: string; description?: string | null; capability_scope?: string; metadata?: PublicRecord } };
  update_knowledge_base: { knowledgeBaseId: string; body: { name?: string; description?: string | null; status?: 'active' | 'archived'; capability_scope?: string; metadata?: PublicRecord } };
  archive_knowledge_base: { knowledgeBaseId: string };
  search_knowledge_base: { knowledgeBaseId: string; selectedPdModelId: string; body: { query: string; query_type?: 'answer' | 'policy_check' | 'tool_discovery' | 'skill_discovery'; document_ids?: string[]; [key: string]: unknown } };
  upsert_knowledge_entries: { knowledgeBaseId: string; body: { entries: PublicRecord[] }; idempotencyKey?: string };
  list_knowledge_versions: { knowledgeBaseId: string };
  rollback_knowledge_base: { knowledgeBaseId: string; version: string };
  list_knowledge_documents: { knowledgeBaseId: string };
  update_knowledge_document: { knowledgeBaseId: string; documentId: string; body: { title?: string; status?: 'ready' | 'processing' | 'failed' | 'archived'; metadata?: PublicRecord; content_md?: string; expected_updated_at?: string } };
  archive_knowledge_document: { knowledgeBaseId: string; documentId: string };
  list_knowledge_concepts: { knowledgeBaseId: string };
  get_knowledge_document: { knowledgeBaseId: string; documentId: string };
  upload_knowledge_document: { knowledgeBaseId: string; body: { filename: string; content_base64: string; title?: string | null } };
  import_knowledge_okf: { knowledgeBaseId: string; body: { filename: string; content_base64: string } };
  list_document_buckets: { documentId: string };
  list_bucket_chunks: { bucketId: string };
  update_knowledge_bucket: { bucketId: string; body: PublicRecord };
  update_knowledge_chunk: { chunkId: string; body: PublicRecord };
  get_knowledge_concept: { knowledgeBaseId: string; conceptId: string };
  update_knowledge_concept: { knowledgeBaseId: string; conceptId: string; body: { content_md: string; document_id?: string; status?: string } };
  export_knowledge_okf: { knowledgeBaseId: string };
  list_knowledge_jobs: { status?: string; limit?: number };
  get_knowledge_job: { jobId: string };
  cancel_knowledge_job: { jobId: string };
  list_knowledge_discoveries: { knowledgeBaseId?: string; status?: string };
  confirm_knowledge_discovery: { suggestionId: string };
  reject_knowledge_discovery: { suggestionId: string };
  list_sops: {};
  get_sop_draft: { sopId: string; draftId: string };
  list_sop_versions: { sopId: string };
  get_sop_version: { sopId: string; version: string };
  create_sop_draft: { body: { content: PublicRecord } };
  replace_sop_draft: { sopId: string; draftId: string; etag: string; body: { content: PublicRecord } };
  publish_sop: { sopId: string; draftId: string };
  archive_sop: { sopId: string };
  rollback_sop_version: { sopId: string; version: string };
  create_tool: { body: Record<string, unknown> };
  update_tool: { toolId: string; body: Record<string, unknown> };
  test_tool: { toolId: string; body: Record<string, unknown> };
  import_general_skill: { body: Record<string, unknown> };
  publish_general_skill: { slug: string };
  archive_general_skill: { slug: string };
  test_general_skill: { slug: string; body: Record<string, unknown> };
  generate_sop: { body: { title: string; raw_content: string; business_domain?: string | null; model_config_id?: string | null } };
  rewrite_saved_sop: { sopId: string; body: { instruction: string; target_paths?: string[]; model_config_id?: string | null; draft_id?: string | null }; dirty?: false };
  get_job: { jobId: string };
  get_job_result: { jobId: string };
  job_events: { jobId: string; lastEventId?: string | number };
  cancel_job: { jobId: string };
  preview_generate_sop: { body: {
    title: string; raw_content: string; business_domain?: string | null; model_config_id?: string | null;
    available_tools?: Record<string, unknown>[]; available_general_skills?: Record<string, unknown>[];
    available_knowledge_bases?: Record<string, unknown>[];
  } };
  preview_rewrite_sop: { sopId: string; body: {
    current_skill: Record<string, unknown> & { skill_id: string }; instruction: string;
    model_config_id?: string | null; target_path?: string; target_paths?: string[];
    target_label?: string | null; conversation?: Array<Record<string, string>>;
    available_tools?: Record<string, unknown>[]; available_sops?: Record<string, unknown>[];
  } };
  get_preview_job: { jobId: string };
  preview_job_events: { jobId: string; afterSeq?: number };
  cancel_preview_job: { jobId: string };
  move_to_draft_sop: { sopId: string };
  remove_sop: { sopId: string };
  sync_sop_from_overall: { sopId: string };
  promote_sop_to_overall: { sopId: string };
  delete_sop_version: { sopId: string; version: string };
  probe_unsaved_tool: { body: Record<string, unknown> };
  remove_tool: { toolId: string };
  extract_sop_text: { body: { filename: string; content_base64: string } };
  list_model_catalog: {};
  list_handoff_users: {};
};
export type PublicOperation = keyof PublicOperationInput;
export type PublicSelectedScope = { kind: 'agent'; agentId: string } | { kind: 'team' };
export type PublicRecord = Record<string, unknown>;
export type PublicCollection = { data: PublicRecord[]; next_cursor?: string | null };
export type PublicJob = PublicRecord & { id: string; status: string };
export type PublicKnowledgeIngestJob = PublicJob & {
  tenant_id: string; knowledge_base_id: string; document_id?: string | null;
  filename: string; stage: string; progress: number; error?: string | null;
  metadata: PublicRecord; created_at: string; started_at?: string | null;
  finished_at?: string | null; updated_at: string;
};
export type PublicPdModelCatalog = {
  data: Array<{ id: string; provider: string; model: string; available?: boolean; enabled?: boolean; is_default?: boolean }>;
  defaultSelection?: { mode?: 'model'; provider: string; model: string };
};
export type PublicKnowledgeSearchResult = PublicRecord & {
  host_model_selection: { id: string; model_use: 'pilotdeck_dialogue_only'; retrieval_mode: 'staffdeck_public_lexical' };
};
export type PublicPreviewJob = PublicRecord & { job_id: string; status: string; last_seq: number };
export type PublicJobResult = { job: PublicJob; result: PublicRecord; error: PublicRecord };
export type PublicSopDraft = PublicRecord & { id: string; agent_id: string; sop_id: string; content: PublicRecord; etag: string; status: string };
export type PublicOperationOutput = {
  list_tools: PublicCollection; list_general_skills: PublicCollection; list_knowledge_bases: PublicCollection;
  create_knowledge_base: PublicRecord; update_knowledge_base: PublicRecord; archive_knowledge_base: PublicRecord;
  search_knowledge_base: PublicKnowledgeSearchResult; upsert_knowledge_entries: PublicJob; list_knowledge_versions: PublicCollection;
  rollback_knowledge_base: PublicRecord; list_knowledge_documents: PublicCollection;
  update_knowledge_document: PublicRecord; archive_knowledge_document: PublicRecord; list_knowledge_concepts: PublicCollection;
  get_knowledge_document: PublicRecord; upload_knowledge_document: PublicKnowledgeIngestJob; import_knowledge_okf: PublicRecord;
  list_document_buckets: PublicCollection; list_bucket_chunks: PublicCollection; update_knowledge_bucket: PublicRecord;
  update_knowledge_chunk: PublicRecord; get_knowledge_concept: PublicRecord; update_knowledge_concept: PublicRecord;
  export_knowledge_okf: { content_base64: string; media_type: string; filename?: string | null };
  list_knowledge_jobs: PublicCollection; get_knowledge_job: PublicRecord; cancel_knowledge_job: PublicRecord;
  list_knowledge_discoveries: PublicCollection; confirm_knowledge_discovery: PublicRecord; reject_knowledge_discovery: PublicRecord;
  list_sops: PublicCollection & { drafts: PublicRecord[] };
  get_sop_draft: PublicSopDraft; list_sop_versions: PublicCollection; get_sop_version: PublicRecord;
  create_sop_draft: PublicSopDraft; replace_sop_draft: PublicSopDraft;
  publish_sop: { sop: PublicRecord; draft: PublicSopDraft };
  archive_sop: PublicRecord; rollback_sop_version: PublicSopDraft;
  create_tool: PublicRecord; update_tool: PublicRecord; test_tool: PublicRecord;
  import_general_skill: PublicRecord; publish_general_skill: PublicRecord;
  archive_general_skill: PublicRecord; test_general_skill: PublicRecord;
  generate_sop: PublicJob; rewrite_saved_sop: PublicJob;
  get_job: PublicJob; get_job_result: PublicJobResult; job_events: unknown; cancel_job: PublicJob;
  preview_generate_sop: { job_id: string }; preview_rewrite_sop: { job_id: string };
  get_preview_job: PublicPreviewJob; preview_job_events: unknown;
  cancel_preview_job: { status: 'cancel_requested'; job_id: string };
  move_to_draft_sop: PublicRecord; remove_sop: PublicRecord;
  sync_sop_from_overall: PublicRecord; promote_sop_to_overall: PublicRecord;
  delete_sop_version: PublicRecord; probe_unsaved_tool: PublicRecord;
  remove_tool: PublicRecord; extract_sop_text: { filename: string; text: string };
  list_model_catalog: PublicCollection; list_handoff_users: PublicCollection;
};
export type PublicResponse<T = unknown> = { status: number; body: T; headers?: Headers | Record<string, string> };
export type PublicTransportPlan = {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'; path: string;
  headers: Record<string, string>; body?: Record<string, unknown>;
  shape?: string; responseType?: 'event-stream'; signal?: AbortSignal;
};
export class PublicCapabilityError extends Error { code: string; status: number; }
export const PUBLIC_OPERATION_CONTRACTS: Readonly<Record<PublicOperation, readonly [string, string, string, string]>>;
export const PUBLIC_APPROVED_OPERATIONS: readonly PublicOperation[];
export const PUBLIC_PROTOCOL_BLOCKERS: Readonly<Record<string, string>>;
export function planPublicOperation<O extends PublicOperation>(agentId: string | null, operation: O, input: PublicOperationInput[O]): PublicTransportPlan;
export function createPublicCapabilityClient(options: {
  agentId: string;
  transport: (plan: PublicTransportPlan) => Promise<PublicResponse>;
  authorizedOperations?: readonly PublicOperation[];
  fixedTargetAgentId?: string;
  /** Must read the selected PD runtime Port/Gateway catalog for this request. */
  hostModelCatalog?: (options: { signal?: AbortSignal }) => Promise<PublicPdModelCatalog>;
}): {
  call<O extends PublicOperation>(operation: O, input: PublicOperationInput[O], options?: { signal?: AbortSignal; scope?: PublicSelectedScope }): Promise<PublicResponse<PublicOperationOutput[O] | PublicRecord>>;
};
export type PublicSseEvent = { id?: string; event: string; data: string };
export type PreviewSseEvent = PublicSseEvent & { sequence?: number };
export function decodePublicJobEvents(chunks: AsyncIterable<Uint8Array | string>, options?: { signal?: AbortSignal }): AsyncIterable<PublicSseEvent>;
export function decodePreviewJobEvents(chunks: AsyncIterable<Uint8Array | string>, options?: { signal?: AbortSignal }): AsyncIterable<PreviewSseEvent>;
